// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: pkg/controller/rpc/student/student.proto

package student

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StudentID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *StudentID) Reset() {
	*x = StudentID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_controller_rpc_student_student_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StudentID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentID) ProtoMessage() {}

func (x *StudentID) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_controller_rpc_student_student_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentID.ProtoReflect.Descriptor instead.
func (*StudentID) Descriptor() ([]byte, []int) {
	return file_pkg_controller_rpc_student_student_proto_rawDescGZIP(), []int{0}
}

func (x *StudentID) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type StudentName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *StudentName) Reset() {
	*x = StudentName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_controller_rpc_student_student_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StudentName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentName) ProtoMessage() {}

func (x *StudentName) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_controller_rpc_student_student_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentName.ProtoReflect.Descriptor instead.
func (*StudentName) Descriptor() ([]byte, []int) {
	return file_pkg_controller_rpc_student_student_proto_rawDescGZIP(), []int{1}
}

func (x *StudentName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StudentParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Gender string `protobuf:"bytes,2,opt,name=gender,proto3" json:"gender,omitempty"`
}

func (x *StudentParam) Reset() {
	*x = StudentParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_controller_rpc_student_student_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StudentParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentParam) ProtoMessage() {}

func (x *StudentParam) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_controller_rpc_student_student_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentParam.ProtoReflect.Descriptor instead.
func (*StudentParam) Descriptor() ([]byte, []int) {
	return file_pkg_controller_rpc_student_student_proto_rawDescGZIP(), []int{2}
}

func (x *StudentParam) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StudentParam) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

type StudentModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt int32  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt int32  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Name      string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Gender    string `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
}

func (x *StudentModel) Reset() {
	*x = StudentModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_controller_rpc_student_student_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StudentModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentModel) ProtoMessage() {}

func (x *StudentModel) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_controller_rpc_student_student_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentModel.ProtoReflect.Descriptor instead.
func (*StudentModel) Descriptor() ([]byte, []int) {
	return file_pkg_controller_rpc_student_student_proto_rawDescGZIP(), []int{3}
}

func (x *StudentModel) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StudentModel) GetCreatedAt() int32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *StudentModel) GetUpdatedAt() int32 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *StudentModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StudentModel) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

type StudentModels struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Students []*StudentModel `protobuf:"bytes,1,rep,name=students,proto3" json:"students,omitempty"`
}

func (x *StudentModels) Reset() {
	*x = StudentModels{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_controller_rpc_student_student_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StudentModels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentModels) ProtoMessage() {}

func (x *StudentModels) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_controller_rpc_student_student_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentModels.ProtoReflect.Descriptor instead.
func (*StudentModels) Descriptor() ([]byte, []int) {
	return file_pkg_controller_rpc_student_student_proto_rawDescGZIP(), []int{4}
}

func (x *StudentModels) GetStudents() []*StudentModel {
	if x != nil {
		return x.Students
	}
	return nil
}

var File_pkg_controller_rpc_student_student_proto protoreflect.FileDescriptor

var file_pkg_controller_rpc_student_student_proto_rawDesc = []byte{
	0x0a, 0x28, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72,
	0x2f, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x2f, 0x73, 0x74, 0x75,
	0x64, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6d, 0x79, 0x73, 0x63,
	0x68, 0x6f, 0x6f, 0x6c, 0x22, 0x1b, 0x0a, 0x09, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49,
	0x44, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x21, 0x0a, 0x0b, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3a, 0x0a, 0x0c, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x22, 0x88, 0x01, 0x0a, 0x0c, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x22, 0x43, 0x0a, 0x0d, 0x53,
	0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x12, 0x32, 0x0a, 0x08,
	0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x6d, 0x79, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x2e, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e,
	0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x08, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x73,
	0x32, 0xed, 0x01, 0x0a, 0x07, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x12, 0x38, 0x0a, 0x06,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x16, 0x2e, 0x6d, 0x79, 0x73, 0x63, 0x68, 0x6f, 0x6f,
	0x6c, 0x2e, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x1a, 0x16,
	0x2e, 0x6d, 0x79, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x2e, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e,
	0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x33, 0x0a, 0x04, 0x52, 0x65, 0x61, 0x64, 0x12, 0x13,
	0x2e, 0x6d, 0x79, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x2e, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e,
	0x74, 0x49, 0x44, 0x1a, 0x16, 0x2e, 0x6d, 0x79, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x2e, 0x53,
	0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x35, 0x0a, 0x06, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x13, 0x2e, 0x6d, 0x79, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c,
	0x2e, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x1a, 0x16, 0x2e, 0x6d, 0x79, 0x73,
	0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x2e, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x12, 0x3c, 0x0a, 0x0a, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x15, 0x2e, 0x6d, 0x79, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x2e, 0x53, 0x74, 0x75, 0x64,
	0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x17, 0x2e, 0x6d, 0x79, 0x73, 0x63, 0x68, 0x6f,
	0x6f, 0x6c, 0x2e, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x42, 0x1d, 0x5a, 0x1b, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x6c, 0x65, 0x72, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_controller_rpc_student_student_proto_rawDescOnce sync.Once
	file_pkg_controller_rpc_student_student_proto_rawDescData = file_pkg_controller_rpc_student_student_proto_rawDesc
)

func file_pkg_controller_rpc_student_student_proto_rawDescGZIP() []byte {
	file_pkg_controller_rpc_student_student_proto_rawDescOnce.Do(func() {
		file_pkg_controller_rpc_student_student_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_controller_rpc_student_student_proto_rawDescData)
	})
	return file_pkg_controller_rpc_student_student_proto_rawDescData
}

var file_pkg_controller_rpc_student_student_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_controller_rpc_student_student_proto_goTypes = []interface{}{
	(*StudentID)(nil),     // 0: myschool.StudentID
	(*StudentName)(nil),   // 1: myschool.StudentName
	(*StudentParam)(nil),  // 2: myschool.StudentParam
	(*StudentModel)(nil),  // 3: myschool.StudentModel
	(*StudentModels)(nil), // 4: myschool.StudentModels
}
var file_pkg_controller_rpc_student_student_proto_depIdxs = []int32{
	3, // 0: myschool.StudentModels.students:type_name -> myschool.StudentModel
	2, // 1: myschool.Student.Create:input_type -> myschool.StudentParam
	0, // 2: myschool.Student.Read:input_type -> myschool.StudentID
	0, // 3: myschool.Student.Delete:input_type -> myschool.StudentID
	1, // 4: myschool.Student.FindByName:input_type -> myschool.StudentName
	3, // 5: myschool.Student.Create:output_type -> myschool.StudentModel
	3, // 6: myschool.Student.Read:output_type -> myschool.StudentModel
	3, // 7: myschool.Student.Delete:output_type -> myschool.StudentModel
	4, // 8: myschool.Student.FindByName:output_type -> myschool.StudentModels
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_controller_rpc_student_student_proto_init() }
func file_pkg_controller_rpc_student_student_proto_init() {
	if File_pkg_controller_rpc_student_student_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_controller_rpc_student_student_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StudentID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_controller_rpc_student_student_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StudentName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_controller_rpc_student_student_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StudentParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_controller_rpc_student_student_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StudentModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_controller_rpc_student_student_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StudentModels); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_controller_rpc_student_student_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_controller_rpc_student_student_proto_goTypes,
		DependencyIndexes: file_pkg_controller_rpc_student_student_proto_depIdxs,
		MessageInfos:      file_pkg_controller_rpc_student_student_proto_msgTypes,
	}.Build()
	File_pkg_controller_rpc_student_student_proto = out.File
	file_pkg_controller_rpc_student_student_proto_rawDesc = nil
	file_pkg_controller_rpc_student_student_proto_goTypes = nil
	file_pkg_controller_rpc_student_student_proto_depIdxs = nil
}
